feat: add features field
denoland/deno_config pull request #14
Opened 2023-10-04 09:12 UTC by kt3k

We'd like to read feature flag from deno.json(c). This PR adds reading of `features` field.

Related: https://github.com/denoland/deno/issues/20779

2023-10-04 10:46 UTC, bartlomieju requested changes
Marking as "Request changes" cause we need a bit of bike-shedding on the name. Otherwise LGTM

2023-10-04 14:19 UTC, dsherret commented on src/lib.rs
> +  pub features: Vec<String>,
Maybe `unstable`?

2023-10-05 03:23 UTC, dsherret approved these changes
LGTM!

2023-10-05 08:21 UTC, bartlomieju approved these changes
LGTM

2023-10-05 09:40 UTC, merged